## 3 Matrix Vector Operations

In [1]:
## import all the modules 
import numpy as np
from numpy import linalg
import math

Intro: Timmy two space game:
http://edx-org-utaustinx.s3.amazonaws.com/UT501x/Spring2015/Timmy/index.html

### 3.1 Special Matrix

- #### Zeroo matrix

In [11]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

- #### Identity Matrix

In [12]:
np.eye(5,5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

#### Vector x times Identity matrix I equals to itself

- #### Diagonal matrices 

In [13]:
v = [1,2,3,4,5]
np.diag(v)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

- #### Traingular Matrix

In [43]:
## upper traingular matrix 

v = np.arange(25).reshape(5,5)
# upper traingular matrix 
np.triu(v,k=0)

array([[ 0,  1,  2,  3,  4],
       [ 0,  6,  7,  8,  9],
       [ 0,  0, 12, 13, 14],
       [ 0,  0,  0, 18, 19],
       [ 0,  0,  0,  0, 24]])

In [44]:
# strict upper traingular matrix 
np.triu(v,k=1)

array([[ 0,  1,  2,  3,  4],
       [ 0,  0,  7,  8,  9],
       [ 0,  0,  0, 13, 14],
       [ 0,  0,  0,  0, 19],
       [ 0,  0,  0,  0,  0]])

In [46]:
# lower traingular matrix 
np.tril(v,k=0)

array([[ 0,  0,  0,  0,  0],
       [ 5,  6,  0,  0,  0],
       [10, 11, 12,  0,  0],
       [15, 16, 17, 18,  0],
       [20, 21, 22, 23, 24]])

In [48]:
# strict lower traingular matrix 
np.tril(v,k=-1)

array([[ 0,  0,  0,  0,  0],
       [ 5,  0,  0,  0,  0],
       [10, 11,  0,  0,  0],
       [15, 16, 17,  0,  0],
       [20, 21, 22, 23,  0]])

In [53]:
# unit lower/upper traingular matrix 
# use fill_diagonal
a = np.tril(v,k=-1)
np.fill_diagonal(a,1)
a

array([[ 1,  0,  0,  0,  0],
       [ 5,  1,  0,  0,  0],
       [10, 11,  1,  0,  0],
       [15, 16, 17,  1,  0],
       [20, 21, 22, 23,  1]])

- #### Transpose a matrix:
    - #### Defination:  simply: two matrix A, B, if a_{i,j}=b_{j,i}, Then $B=A^T$

In [4]:
## Matrix transpose 
A = np.arange(25).reshape(5,5)
A_t = A.transpose()
print("A= \n",A)
print('A^T= \n',A_t)


A= 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
A^T= 
 [[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


- #### Symmetric Matrices

In [61]:
N = 5
b = np.arange(N**2).reshape(N,N)
b_symm = (b + b.T)/2
b_symm

array([[  0.,   3.,   6.,   9.,  12.],
       [  3.,   6.,   9.,  12.,  15.],
       [  6.,   9.,  12.,  15.,  18.],
       [  9.,  12.,  15.,  18.,  21.],
       [ 12.,  15.,  18.,  21.,  24.]])

- #### How to scale a Matrix : it is basically multiple the scaler to each element of the matrix
- #### How to add two Matrices : it is basically adding each element of the two matrices